# Generated by Django 2.0.6 on 2018-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='users_app/media/images/default_user_pic.jpg', upload_to='users_app/media/images/'),
        ),
    ]
