# Generated by Django 2.0.6 on 2018-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_auto_20180812_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='images/users_app/default_user_pic.jpg', upload_to='images/users_app/'),
        ),
    ]
