# Generated by Django 2.0.6 on 2018-07-31 19:48

import car_dealer_app.utils
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('SRA', 'Sales_rent_agent'), ('SA', 'Sales_agent'), ('RA', 'Rental_agent')], max_length=15)),
                ('image', models.ImageField(default='images/default_user_pic.jpg', upload_to='images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_app.Make')),
            ],
        ),
        migrations.CreateModel(
            name='RentalVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('A', 'Automobile'), ('M', 'Motorcycle'), ('B', 'Bus'), ('T', 'Truck')], max_length=1)),
                ('engine_type', models.CharField(choices=[('D', 'Disel'), ('P', 'Petrol'), ('E', 'Electric'), ('H', 'Hybrid')], max_length=1)),
                ('transmission', models.CharField(choices=[('A', 'Auto'), ('M', 'Manual'), ('S', 'Semi-auto')], max_length=1)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('reg_number', models.CharField(default='', max_length=10, unique=True)),
                ('year', models.PositiveIntegerField(null=True, validators=[car_dealer_app.utils.curr_year_validator])),
                ('image', models.ImageField(default='images/default_image.jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('rental_price_per_day', models.PositiveIntegerField()),
                ('rental_status', models.BooleanField(default=False)),
                ('rented_at', models.DateTimeField(default=None, null=True)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_type', models.CharField(choices=[('A', 'Automobile'), ('M', 'Motorcycle'), ('B', 'Bus'), ('T', 'Truck')], max_length=1)),
                ('engine_type', models.CharField(choices=[('D', 'Disel'), ('P', 'Petrol'), ('E', 'Electric'), ('H', 'Hybrid')], max_length=1)),
                ('transmission', models.CharField(choices=[('A', 'Auto'), ('M', 'Manual'), ('S', 'Semi-auto')], max_length=1)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('reg_number', models.CharField(default='', max_length=10, unique=True)),
                ('year', models.PositiveIntegerField(null=True, validators=[car_dealer_app.utils.curr_year_validator])),
                ('image', models.ImageField(default='images/default_image.jpg', upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveIntegerField(null=True)),
                ('sell_status', models.CharField(choices=[('A', 'Active'), ('S', 'Sold'), ('P', 'Pending'), ('N', 'Neutral')], default='A', max_length=1)),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Model')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
