# Generated by Django 2.0.6 on 2018-07-23 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=15)),
                ('v_type', models.CharField(choices=[('A', 'Automobile'), ('M', 'Motorcycle'), ('B', 'Bus'), ('T', 'Truck')], max_length=2)),
                ('engine_type', models.CharField(choices=[('D', 'Diesl'), ('P', 'Petrol'), ('E', 'Electric'), ('H', 'Hybrid')], max_length=1)),
                ('transmission', models.CharField(choices=[('A', 'Auto'), ('M', 'Manual'), ('S', 'Semi-auto')], max_length=1)),
                ('condition', models.CharField(choices=[('N', 'New'), ('U', 'Used')], max_length=1)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator('2018')])),
                ('price', models.PositiveIntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
