# Generated by Django 2.0.6 on 2018-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalvehicle',
            name='rented_until',
            field=models.DateField(default=None, null=True),
        ),
    ]
