# Generated by Django 2.0.6 on 2018-07-30 07:13

import car_dealer_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[car_dealer_app.utils.curr_year_validator]),
        ),
    ]
