# Generated by Django 2.0.6 on 2018-07-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
