# Generated by Django 2.0.6 on 2018-08-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0002_rentalvehicle_rented_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='rented_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
