# Generated by Django 2.1 on 2018-08-21 10:56

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0002_auto_20180821_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=image_cropping.fields.ImageCropField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=image_cropping.fields.ImageCropField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
    ]
