# Generated by Django 2.0.6 on 2018-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0002_auto_20180810_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='car_dealer_app/media/images/default_image.jpg', upload_to='car_dealer_app/media/images/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='car_dealer_app/media/images/default_image.jpg', upload_to='car_dealer_app/media/images/'),
        ),
    ]
