# Generated by Django 2.0.6 on 2018-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0003_auto_20180812_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
