# Generated by Django 2.1 on 2018-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0003_auto_20180821_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalvehicle',
            name='cropping',
        ),
        migrations.RemoveField(
            model_name='sellvehicle',
            name='cropping',
        ),
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
    ]
