# Generated by Django 2.0.6 on 2018-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0004_auto_20180812_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='images/car_dealer_app/default_image.jpg', upload_to='images/car_dealer_app/'),
        ),
    ]
