# Generated by Django 2.0.6 on 2018-07-23 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0004_auto_20180723_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.CharField(max_length=4, null=True, validators=[django.core.validators.MaxValueValidator('2018')]),
        ),
    ]
