# Generated by Django 2.0.6 on 2018-08-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0004_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='model',
            new_name='object_type',
        ),
    ]
