# Generated by Django 2.0.6 on 2018-08-03 11:42

import car_dealer_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0005_auto_20180802_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalvehicle',
            name='rented_until',
            field=models.DateTimeField(default=None, null=True, validators=[car_dealer_app.utils.curr_day_validator]),
        ),
    ]
