# Generated by Django 2.0.6 on 2018-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0006_auto_20180803_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='images/users/default_user_pic.jpg', upload_to='images/users/'),
        ),
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='images/cars/default_image.jpg', upload_to='images/cars/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='images/cars/default_image.jpg', upload_to='images/cars/'),
        ),
    ]
