# Generated by Django 2.0.6 on 2018-07-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0006_auto_20180723_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='reg_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
