# Generated by Django 2.0.6 on 2018-07-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0007_auto_20180723_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Make')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='brand',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Model'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='car_dealer_app.Make'),
        ),
    ]
