# Generated by Django 2.0.6 on 2018-08-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0007_auto_20180806_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='images/default_user_pic.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rentalvehicle',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sellvehicle',
            name='image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
