# Generated by Django 2.0.6 on 2018-07-24 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_dealer_app', '0008_auto_20180723_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
