# Generated by Django 2.0.6 on 2018-08-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0009_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='user',
        ),
    ]
