# Generated by Django 2.0.6 on 2018-08-07 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0010_auto_20180806_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
