# Generated by Django 2.0.6 on 2018-07-25 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0012_vehicle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='sold',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sell_status',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Sold'), ('P', 'Pending'), ('D', 'Declined')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1885), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
