# Generated by Django 2.0.6 on 2018-07-26 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer_app', '0013_auto_20180725_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sold_for',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_app.Make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('D', 'Disel'), ('P', 'Petrol'), ('E', 'Electric'), ('H', 'Hybrid')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car_dealer_app.Make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_dealer_app.Model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='v_type',
            field=models.CharField(choices=[('A', 'Automobile'), ('M', 'Motorcycle'), ('B', 'Bus'), ('T', 'Truck')], max_length=1),
        ),
    ]
